# Generated by Django 6.0.4 on 2026-04-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_remove_palco_acessibilidade_mobilidade_reduzida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dia',
            options={'ordering': ['data']},
        ),
        migrations.AlterUniqueTogether(
            name='concerto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dia',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='palco',
            name='imagem',
        ),
        migrations.AddField(
            model_name='palco',
            name='acessibilidade_mobilidade_reduzida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='concerto',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.banda'),
        ),
        migrations.AlterField(
            model_name='concerto',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.dia'),
        ),
        migrations.AlterField(
            model_name='concerto',
            name='palco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.palco'),
        ),
        migrations.AlterField(
            model_name='palco',
            name='capacidade',
            field=models.IntegerField(),
        ),
    ]
